#' @title Fit model at tier level
#' @description Fits spatio-temporal models to data at a tier level for benthic groups.
#' Selects and fits model types 1 to 6 based on `MODEL_TYPE` and scales up the predictions.
#'
#' For MODEL_TYPE == 6 (the production path), each benthic group is fitted in a
#' **separate R subprocess** to avoid OOM from R memory fragmentation.
#' When each subprocess exits, ALL its memory is returned to the OS — no
#' accumulation across groups.
#'
#' Supports hierarchical checkpoints for Stage 4 (ch_4.0, ch_4.1a/b, ch_4.2a/b, ch_4.3a/b, ch_4.4, ch_4.5)
#' @examples
#' model_fitModelTier()
#' @author Julie Vercelloni
#' @export
model_fitModelTier <- function() {

  # ---- Load input data tables for modelling ----
  reefCloudPackage::load_data_for_model()

  # ---- Save ch_4.0 checkpoint (data loaded) ----
  if (exists("CHECKPOINT_START", envir = .GlobalEnv) && CHECKPOINT_START == 0) {
    cat("\n")
    cat(strrep("=", 80), "\n")
    cat("SAVING ch_4.0 CHECKPOINT (Data Loaded for Modeling)\n")
    cat(strrep("=", 80), "\n")

    # Save modeling data environment
    ch_4.0_data <- list(
      data = if(exists("data", envir = .GlobalEnv)) data else NULL,
      GROUPS = GROUPS,
      tiers.lookup = tiers.lookup,
      tier5.sf = tier5.sf,
      reef_layer.sf = reef_layer.sf,
      COVARIATES = if(exists("COVARIATES", envir = .GlobalEnv)) COVARIATES else NULL,
      RDATA_COV_FILE = if(exists("RDATA_COV_FILE", envir = .GlobalEnv)) RDATA_COV_FILE else NULL
    )

    saveRDS(ch_4.0_data, file = paste0(DATA_PATH, "processed/ch_4.0_data.rds"))

    # Upload to S3
    if (exists("ORIGINAL_DATA_PATH", envir = .GlobalEnv) && grepl("^s3://", ORIGINAL_DATA_PATH)) {
      s3_path <- paste0(ORIGINAL_DATA_PATH, "/checkpoint/ch_4.0/processed/ch_4.0_data.rds")
      cmd <- sprintf('aws s3 cp "%s" "%s" --quiet',
                     paste0(DATA_PATH, "processed/ch_4.0_data.rds"), s3_path)
      system(cmd)
      cat("  -> Saved ch_4.0 checkpoint to S3\n")
    }
    cat(strrep("=", 80), "\n\n")
  }

  # ---- Define target benthic groups ----
  # Model only Hard Coral, Soft Coral, and Macroalgae
  GROUP_NAMES <- c("HARD CORAL", "SOFT CORAL", "MACROALGAE")
  GROUP_IDS <- c("4.1", "4.2", "4.3")  # ch_4.1, ch_4.2, ch_4.3

  # ==========================================================================
  # MODEL_TYPE == 6: Subprocess per group (memory isolation)
  # ==========================================================================
  if (MODEL_TYPE == 6) {

    # Ensure environment variables are set for child processes.
    # parseCLA sets R globals via <<- but doesn't export them as env vars.
    # The subprocess uses Sys.getenv() → parseCLA to reconstruct globals.
    Sys.setenv(
      DATA_PATH          = if (exists("DATA_PATH"))          DATA_PATH          else "/data",
      DOMAIN             = if (exists("DOMAIN_CATEGORY"))    DOMAIN_CATEGORY    else "tier",
      BY_TIER            = if (exists("BY_TIER"))            BY_TIER            else "5",
      MODEL_TYPE         = paste0("type", MODEL_TYPE),
      DEBUG              = if (exists("DEBUG_MODE"))         ifelse(DEBUG_MODE, "true", "false") else "false",
      ORIGINAL_DATA_PATH = if (exists("ORIGINAL_DATA_PATH")) ORIGINAL_DATA_PATH else "",
      BASIS_RESOLUTION   = if (exists("BASIS_RESOLUTION"))  as.character(BASIS_RESOLUTION) else "3",
      SINGLE_TIER        = if (exists("SINGLE_TIER"))       SINGLE_TIER        else "",
      PRECISION_RIDGE    = if (exists("PRECISION_RIDGE"))   as.character(PRECISION_RIDGE) else "0"
    )

    for (group_idx in seq_along(GROUP_NAMES)) {
      group_name <- GROUP_NAMES[group_idx]
      group_id   <- GROUP_IDS[group_idx]

      if (!group_name %in% GROUPS) {
        cat(sprintf("  Group '%s' not in data, skipping\n", group_name))
        next
      }

      cat(sprintf("\n%s\n", strrep("#", 80)))
      cat(sprintf("### LAUNCHING SUBPROCESS for group: %s\n", group_name))
      cat(sprintf("### Memory isolation: subprocess will exit after group, freeing all RAM\n"))
      cat(sprintf("%s\n\n", strrep("#", 80)))

      # ---- Write temp Rscript for subprocess ----
      script_file <- tempfile(pattern = paste0("group_", gsub(" ", "_", group_name), "_"),
                              fileext = ".R")

      # Dev-mode block: same logic as 00_main.R lines 9-45
      script_lines <- c(
        '## Subprocess for group fitting — generated by model_fitModelTier()',
        'library(status)',
        '',
        '# Dev-mode: override installed package functions with source files',
        'if (file.exists("/home/project/DESCRIPTION") && dir.exists("/home/project/R")) {',
        '  message("Subprocess: Loading dev-mode source files...")',
        '  library(reefCloudPackage)',
        '  r_files <- list.files("/home/project/R", pattern = "\\\\.[Rr]$", full.names = TRUE)',
        '  pkg_env <- new.env(parent = asNamespace("reefCloudPackage"))',
        '  for (f in r_files) {',
        '    tryCatch(source(f, local = pkg_env), error = function(e) {',
        '      message(sprintf("  Warning: failed to source %s: %s", basename(f), e$message))',
        '    })',
        '  }',
        '  ns <- asNamespace("reefCloudPackage")',
        '  override_count <- 0',
        '  new_count <- 0',
        '  for (fname in ls(pkg_env, all.names = FALSE)) {',
        '    if (is.function(pkg_env[[fname]])) {',
        '      tryCatch({',
        '        assignInNamespace(fname, pkg_env[[fname]], ns = "reefCloudPackage")',
        '        override_count <- override_count + 1',
        '      }, error = function(e) {',
        '        tryCatch({',
        '          environment(pkg_env[[fname]]) <- ns',
        '          assign(fname, pkg_env[[fname]], envir = ns)',
        '          new_count <<- new_count + 1',
        '        }, error = function(e2) {',
        '          message(sprintf("  Warning: could not inject %s: %s", fname, e2$message))',
        '        })',
        '      })',
        '    }',
        '  }',
        '  message(sprintf("Subprocess dev-mode: %d overridden, %d new", override_count, new_count))',
        '} else {',
        '  library(reefCloudPackage)',
        '}',
        '',
        sprintf('reefCloudPackage::run_group_in_subprocess("%s", "%s")',
                group_name, group_id)
      )

      writeLines(script_lines, script_file)

      # ---- Run subprocess ----
      start_time <- Sys.time()
      exit_code <- system2("Rscript", args = script_file, wait = TRUE)
      elapsed <- as.numeric(difftime(Sys.time(), start_time, units = "mins"))

      # Cleanup temp file
      unlink(script_file)

      if (exit_code != 0) {
        msg <- sprintf(
          "SUBPROCESS FAILED: Group '%s' exited with code %d after %.1f min",
          group_name, exit_code, elapsed
        )
        cat(paste0("\n  [ERROR] ", msg, "\n"))
        stop(msg)
      }

      cat(sprintf("\n  -> Group '%s' completed in %.1f min. Subprocess memory freed.\n\n",
                  group_name, elapsed))

      # Log memory state after subprocess exits
      cat(sprintf("  Parent process memory after %s: %.0f MB (R heap)\n",
                  group_name, sum(gc()[, 2])))
    }

    # ---- Post-loop: scale-up and attribution run once across all groups ----
    cat("\n")
    cat(strrep("=", 80), "\n")
    cat("POST-GROUP: Running scale_up_pred and attribute_changes\n")
    cat(strrep("=", 80), "\n\n")

    reefCloudPackage::scale_up_pred("type6")

    # ---- Save ch_4.4 checkpoint (scale-up complete) ----
    cat("\n")
    cat(strrep("=", 80), "\n")
    cat("SAVING ch_4.4 CHECKPOINT (Predictions Scaled Up)\n")
    cat(strrep("=", 80), "\n")

    if (exists("ORIGINAL_DATA_PATH", envir = .GlobalEnv) && grepl("^s3://", ORIGINAL_DATA_PATH)) {
      output_files <- list.files(AWS_OUTPUT_PATH, pattern = "\\.csv$", full.names = TRUE)
      for (out_file in output_files) {
        s3_path <- paste0(ORIGINAL_DATA_PATH, "/checkpoint/ch_4.4/outputs/", basename(out_file))
        cmd <- sprintf('aws s3 cp "%s" "%s" --quiet', out_file, s3_path)
        system(cmd)
      }
      cat("  -> Saved ch_4.4 checkpoint to S3\n")
    }
    cat(strrep("=", 80), "\n\n")

    reefCloudPackage::attribute_changes()

    # ---- Save ch_4.5 checkpoint (attribution complete) ----
    cat("\n")
    cat(strrep("=", 80), "\n")
    cat("SAVING ch_4.5 CHECKPOINT (Attribution Analysis Complete)\n")
    cat(strrep("=", 80), "\n")

    if (exists("ORIGINAL_DATA_PATH", envir = .GlobalEnv) && grepl("^s3://", ORIGINAL_DATA_PATH)) {
      attr_files <- list.files(AWS_OUTPUT_PATH, pattern = "coef_table", full.names = TRUE)
      for (attr_file in attr_files) {
        s3_path <- paste0(ORIGINAL_DATA_PATH, "/checkpoint/ch_4.5/outputs/", basename(attr_file))
        cmd <- sprintf('aws s3 cp "%s" "%s" --quiet', attr_file, s3_path)
        system(cmd)
      }
      cat("  -> Saved ch_4.5 checkpoint to S3\n")
    }
    cat(strrep("=", 80), "\n\n")

  } else {

    # ======================================================================
    # MODEL_TYPE != 6: Direct (non-subprocess) path — legacy types 1-5
    # ======================================================================
    for (group_idx in seq_along(GROUP_NAMES)) {
      assign("GROUP", GROUP_NAMES[group_idx], envir = .GlobalEnv)
      GROUP <- GROUP_NAMES[group_idx]
      group_id <- GROUP_IDS[group_idx]

      if (!GROUP %in% GROUPS) next
      if (!DEBUG_MODE) cli::cli_h1(paste0("Modeling ", GROUP))

      data.grp <- reefCloudPackage::prep_group_data_for_modelling(data, GROUP)

      if (MODEL_TYPE == 1) {
        model_fitModelTier_type1(data.grp)
        reefCloudPackage::scale_up_pred("type1")
      }
      if (MODEL_TYPE == 2) {
        reefCloudPackage::model_fitModelTier_type2(data.grp)
        reefCloudPackage::scale_up_pred("type2")
      }
      if (MODEL_TYPE == 3) {
        reefCloudPackage::model_fitModelTier_type3(data.grp)
        reefCloudPackage::scale_up_pred("type3")
      }
      if (MODEL_TYPE == 4) {
        reefCloudPackage::model_fitModelTier_type4(data.grp)
        reefCloudPackage::scale_up_pred("type4")
      }
      if (MODEL_TYPE == 5) {
        reefCloudPackage::model_fitModelTier_type5(data.grp, tier.sf)
        reefCloudPackage::scale_up_pred("type5")
      }

      # Cleanup between groups
      rm_vars <- c("data.grp")
      for (v in rm_vars) {
        if (exists(v, inherits = FALSE)) rm(list = v)
      }
      gc()
    }
  }
}
